### ISSUE TITLE
No Chaining

### ISSUE THREAD

**Issue by SkyHawkB** [ethamitc/ReflectPlusNPM#1]
It would be great if you could do
```js
const reflect = require('reflectplus');

reflect.error('Test Error', 'My Prefix')
  .error('Test Error', 'My Prefix')
  .error('Test Error', 'My Prefix');
```
but right now that will throw a TypeError.

Please add chaining? ❤️

**Comment by ethamitc** [comment]
Hm, that's not a bad idea. I might implement it in an Experimental release to test.

**Comment by ethamitc** [comment]
This feature is deemed unnecessary and will **not** be added to reflectplus.
